export const actionTypes = {
  SAVE_FETCH: 'SAVE_FETCH',
  SAVE_QUESTION_STATE: 'SAVE_QUESTION_STATE',
  INCREMENT_CHOICES: 'INCREMENT_CHOICES',
  DECREMENT_CHOICES: 'DECREMENT_CHOICES',
  SET_NEW_QUESTION_TITLE: 'SET_NEW_QUESTION_TITLE',
  SET_CHOICE: 'SET_CHOICES',
  MAKE_QUESTION: 'MAKE_QUESTION'
};
